spring:
  datasource:
    dynamic:
      sqlite:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:${sqlite.home}/data/test.db?date_string_format=yyyy-MM-dd HH:mm:ss
        password: 123456
      mysql:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: root
        password: root
    druid:
      # 监控统计拦截的filters
      filters: stat
      keep-alive: true
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          enabled: true
          config:
            multi-statement-allow: true
            delete-allow: true
        slf4j: # slf4j记录日志
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

logging:
  level:
    com.myz.springboot2.mybatis.dynamic.mapper.*: debug